CREATE TABLE IF NOT EXISTS schema_events (
    id TEXT PRIMARY KEY NOT NULL UNIQUE,
    title TEXT NOT NULL,
    url TEXT,
    local_start TIMESTAMP NOT NULL,
    utc_start TIMESTAMP NOT NULL,
    local_end TIMESTAMP,
    utc_end TIMESTAMP,
    timing_type TEXT NOT NULL,
    duration INT,
    time_of_day TEXT NOT NULL,
    day_of_week TEXT NOT NULL,
    event_season TEXT,
    formatted_address TEXT,
    zip TEXT NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    neighborhood TEXT,
    food_bev_density FLOAT NOT NULL,
    food_bev_pop_score FLOAT NOT NULL,
    access_density FLOAT NOT NULL,
    access_pop_score FLOAT NOT NULL,
    lodging_density FLOAT NOT NULL,
    lodging_pop_score FLOAT NOT NULL,
    average_income_zip FLOAT NOT NULL,
    population_zip INT NOT NULL,
    median_age_zip FLOAT NOT NULL,
    event_type TEXT,
    target_audience TEXT NOT NULL,
    event_mood_energy TEXT NOT NULL,
    freebies_included TEXT NOT NULL,
    uniqueness TEXT,
    price FLOAT NOT NULL
);